sudo: required
language: go
before_install:
- curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
- yes id_rsa | ssh-keygen -t rsa -N ""
- cat id_rsa.pub > ~/.ssh/authorized_keys
- mv id_rsa* /home/travis/.ssh/
- chmod g-rw,o-rw /home/travis/.ssh/*
go:
- 1.10.x
services:
- docker
install:
- make deps
- go get github.com/rakyll/statik
script:
- make
addons:
  ssh_known_hosts:
  - localhost
  - 127.0.0.1
  - 0.0.0.0
branches:
  only:
    - master
    - debian/stretch
notifications:
  slack:
    secure: KuxnK08UM90p7fyK8SoqO7jjs+18b1UNRMcPgQvtZ1x4hWOEeEXt+azrDpU6ntWvzTrO8ow5azgYHpKcw2onM/XL4Ic2GQMGiWY+8qsnzr2G/wiuj4Lbq0BuQApal6/XEM8UH5yXundosokgqCD9iapCgr3umGGPkO1qYAEDnXJhZjhv4NhJ3Rn+4zBCmmsH4XkVtDvMueLaMeojofzpj4DvHAPQ4j6UmdaU37JjKI8tYlVt5PzRLu1fKEgn6QDTVjdryew441ubvfxzE1iE+wu/9Xqi9+rihCWfEzku3rK38XkIT3m8dLZmUINald03QV3B1inOBy9pHSpeV/S1XLCy65Bq84gjKzADPCqaAJCoBPKu7xJ7aOBJSmqDBHFbGJcfAJIQP+y3r4svBk+rU6hgt411ySoO8bOkDFR6Mf7W7rQw3Vds0S4n+i5KDO5m6fPmrPAI5kLmXNmAr9ipRQW8OfTPzZyqjBVZ5KYrWZUPPUJGURsCcy3iv3KcxadQIKntcScFy5bqdepR/xQd8cbJB9mu2ioDswsmhZvYZmxnWe9QSmkVuFdg2iiYQ0EVXZmH9Dpo4mcYRL8F3hFJ3D8l0QauPwaleFG+59CwfqY0Di1IH08UnH6x6MbnIF0PnEAV1lYo3jj8d98u3l0kaYJrfQDwQpLxmW05bzuUHA4=
after_success:
- bash <(curl -s https://codecov.io/bash)
