[[constraint]]
  name = "github.com/docker/distribution"
  revision = "6fca8d6e6713acbdf3f9ca40cf6370fc5ee5ee53"

[[constraint]]
  name = "github.com/docker/docker"
  version = "17.05.0-ce"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  name = "github.com/rakyll/statik"
  version = "0.1.1"
